docs_dir: mkdoc
site_dir: docs
site_name: CoolWoods
repo_url: https://github.com/CoolWoods/mkdocs
edit_uri: blob/main/mkdoc/
repo_name: CoolWoods/mkdocs
theme:
  logo: assets/logo.png
  favicon: assets/logo.png
  name: material
  features:
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.instant.preview
    # - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    # - navigation.path
    # - navigation.indexes
    # - toc.follow
    # - toc.integrate
    - navigation.top
    - navigation.footer
    - content.code.copy
    - content.code.select
  language: zh
  highlightjs: true
plugins:
  - search
  - blog
nav:
  # - Section:
  #     - section/index.md
  - 首页: index.md
  - 博客:
      - Markdown语法: Markdown语法.md
      - Mkdocs使用: Mkdocs使用.md
      - python安装: python安装.md
  - java:
      - 多线程: java/多线程.md
      - 流: java/流.md
      - JVM: java/JVM.md
      - Servlet: java/Servlet.md

  - 关于:
      - 更新日志: Release.md
      - License: License.md
not_in_nav: |
  /Tms.md
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      linenums_style: pymdownx-inline
      auto_title: true
      pygments_lang_class: true
      use_pygments: true
#      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.superfences
